version: '3'
services:
  mongo_server:
    container_name: mongo_server
    image: mongo
    volumes:
      - /Users/duynguyen/data/db:/data/db
    ports:
      - "27017:27017"
    # healthcheck:
    #   test: ["CMD", "docker-healthcheck"]
    #   interval: 30s
    #   timeout: s
    #   retries: 3
  booking_service:
    restart: on-failure
    container_name: booking_service
    build:
      context: ./services/booking.api
      dockerfile: Dockerfile
    # volumes:
    #   - /app/node_modules
    #   - ./services/booking.api:/usr/booking_app
    depends_on:
      - mongo_server
    links:
      - mongo_server
    ports:
      - "3000:3000"
  routing_service:
    restart: always
    build:
      context: ./services/routing_service
      dockerfile: Dockerfile
    ports:
      - '3050:80'
    depends_on:
      - mongo_server
      - booking_service


